task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /content/WIDER_train/
    ann_file: /content/annotations/wider_face_train_annot_coco_style.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 4
  drop_last: True

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /content/WIDER_val
    ann_file: /content/annotations/wider_face_val_annot_coco_style.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 4
  num_workers: 4
  drop_last: False
