metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: WIDER_train
  anno_path: annotations/wider_face_train_annot_coco_style.json
  dataset_dir: WIDER
  data_fields: ["image", "gt_bbox", "gt_class", "is_crowd"]

EvalDataset:
  name: COCODataSet
  image_dir: WIDER_val
  anno_path: annotations/wider_face_val_annot_coco_style.json
  dataset_dir: WIDER
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/wider_face_val_annot_coco_style.json # also support txt (like VOC's label_list.txt)
  dataset_dir: WIDER # if set, anno_path will be 'dataset_dir/anno_path'
